name: TeleportTo
main: me.michaelkrauty.TeleportTo.TeleportTo
author: michaelkrauty
version: 1.1
commands:
   to:
     description: Teleport to a player
     usage: /to <player>
   tohere:
     description: Teleport a player to your location
     usage: /tohere <player>